/*
    * This header is generated by classdump-dyld 1.0
    * Operating System: 14.2.1
    * Image Source: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import <QuartzCore/QuartzCore.h>
@class NSString;

@interface CABackdropLayer: CALayer

@property (getter=isEnabled) BOOL enabled; 
@property (copy) NSString *groupName; 
@property  BOOL usesGlobalGroupNamespace; 
@property (copy) NSString *groupNamespace; 
@property  double scale; 
@property  CGRect backdropRect; 
@property  double marginWidth; 
@property  BOOL disablesOccludedBackdropBlurs; 
@property  BOOL captureOnly; 
@property  BOOL allowsInPlaceFiltering; 
@property  BOOL reducesCaptureBitDepth; 
@property  BOOL ignoresScreenClip; 
@property  double bleedAmount; 
@property  BOOL windowServerAware; 
@property (getter=isInverseMeshed) BOOL inverseMeshed; 
@property  BOOL allowsSubstituteColor; 
@property  CGColorRef substituteColor; 
@property  BOOL ignoresOffscreenGroups; 
@property  double zoom; 
@property (weak) id<CALayerDelegate> delegate;
+(void)initialize;
+(id)defaultValueForKey:(id)arg1;
+(id)CA_attributes;
+(BOOL)CA_automaticallyNotifiesObservers:(Class)arg1;
+(BOOL)_hasRenderLayerSubclass;
-(void)didChangeValueForKey:(id)arg1;
-(void)setEnabled:(BOOL)arg1;
-(BOOL)isEnabled;
-(double)scale;
-(void)setScale:(double)arg1;
-(void)setCaptureOnly:(BOOL)arg1;
-(id)groupName;
-(void)layerDidBecomeVisible:(BOOL)arg1;
-(void)setAllowsSubstituteColor:(BOOL)arg1;
-(void)setGroupName:(id)arg1;
-(void)setGroupNamespace:(id)arg1;
-(void)setInverseMeshed:(BOOL)arg1;
-(void)setWindowServerAware:(BOOL)arg1;
-(BOOL)isInverseMeshed;
-(void)setMarginWidth:(double)arg1;
-(void)setBleedAmount:(double)arg1;
-(CGColorRef)substituteColor;
-(void*)_copyRenderLayer:(void*)arg1 layerFlags:(unsigned)arg2 commitFlags:(unsigned*)arg3;
-(void)_renderBackgroundInContext:(CGContextRef)arg1;
-(BOOL)_renderLayerDefinesProperty:(unsigned)arg1;
-(unsigned)_renderLayerPropertyAnimationFlags:(unsigned)arg1;
-(BOOL)allowsInPlaceFiltering;
-(BOOL)allowsSubstituteColor;
-(CGRect)backdropRect;
-(double)bleedAmount;
-(BOOL)captureOnly;
-(BOOL)disablesOccludedBackdropBlurs;
-(id)groupNamespace;
-(BOOL)ignoresOffscreenGroups;
-(BOOL)ignoresScreenClip;
-(double)marginWidth;
-(BOOL)reducesCaptureBitDepth;
-(void)setAllowsInPlaceFiltering:(BOOL)arg1;
-(void)setBackdropRect:(CGRect)arg1;
-(void)setDisablesOccludedBackdropBlurs:(BOOL)arg1;
-(void)setIgnoresOffscreenGroups:(BOOL)arg1;
-(void)setIgnoresScreenClip:(BOOL)arg1;
-(void)setReducesCaptureBitDepth:(BOOL)arg1;
-(void)setSubstituteColor:(CGColorRef)arg1;
-(void)setUsesGlobalGroupNamespace:(BOOL)arg1;
-(void)setZoom:(double)arg1;
-(BOOL)usesGlobalGroupNamespace;
-(BOOL)windowServerAware;
-(double)zoom;
@end

