/*
 * This header is generated by classdump-dyld 1.0
 * Operating System: 14.2.1
 * Image Source: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <Foundation/Foundation.h>
#import <QuartzCore/QuartzCore.h>
#import "NSViewLayerFilter.h"
@class NSString;

NS_ASSUME_NONNULL_BEGIN

extern NSString *const kCAFilterDarkenBlendMode;
extern NSString *const kCAFilterGaussianBlur;
extern NSString *const kCAFilterColorSaturate;
extern NSString *const kCAFilterLightenBlendMode;
extern NSString *const kCAFilterDestOver;

@class NSString;

@interface CAFilter : NSObject <NSViewLayerFilter, NSCopying, NSMutableCopying, NSSecureCoding> {
    unsigned int _type;
    NSString *_name;
    unsigned int _flags;
    void *_attr;
    void *_cache;
}

@property (class, readonly) BOOL supportsSecureCoding;
@property (readonly) BOOL NS_isSourceOver;
@property (readonly) NSString *type;
@property (copy) NSString *name;
@property (getter = isEnabled) BOOL enabled;
@property BOOL cachesInputImage;
@property (getter = isAccessibility) BOOL accessibility;

+ (nullable instancetype)filterWithName:(id)a0;
+ (nullable instancetype)filterWithType:(id)a0;
+ (void)CAMLParserStartElement:(id)a0;
+ (id)attributesForKey:(id)a0;
+ (id)filterTypes;

- (id)copyWithZone:(nullable NSZone *)a0;
- (id)mutableCopyWithZone:(nullable NSZone *)a0;
- (BOOL)enabled;
- (void)encodeWithCoder:(id)a0;
- (nullable instancetype)initWithCoder:(id)a0;
- (nullable instancetype)initWithName:(id)a0;
- (nullable instancetype)initWithType:(id)a0;
- (void)setDefaults;
- (void)CAMLParser:(id)a0 setValue:(id)a1 forKey:(id)a2;
- (id)attributesForKeyPath:(id)a0;
- (id)inputKeys;
- (id)outputKeys;

@end


NS_ASSUME_NONNULL_END
