/*
    * This header is generated by classdump-dyld 1.0
    * Operating System: 14.2.1
    * Image Source: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import <AppKit/AppKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface NSTableViewStyleData: NSObject <NSCopying>

@property  NSTableViewStyle effectiveStyle;                            //@synthesize effectiveStyle=_effectiveStyle - In the implementation block
@property  NSTableViewRowSizeStyle rowSizeStyle;                              //@synthesize rowSizeStyle=_rowSizeStyle - In the implementation block
@property (readonly) NSTableViewStyle tableViewStyle;
@property (readonly) BOOL hasInsetContent;
@property (readonly) BOOL hasPaddedContent; 
@property (readonly) BOOL isSourceList; 
@property  double rowHeight;                                    //@synthesize rowHeight=_rowHeight - In the implementation block
@property  double groupRowHeight;                               //@synthesize groupRowHeight=_groupRowHeight - In the implementation block
@property  double headerHeight;                                 //@synthesize headerHeight=_headerHeight - In the implementation block
@property  CGSize intercellSpacing;                             //@synthesize intercellSpacing=_intercellSpacing - In the implementation block
@property  double intergroupSpacing;                            //@synthesize intergroupSpacing=_intergroupSpacing - In the implementation block
@property  double topPadding;                                   //@synthesize topPadding=_topPadding - In the implementation block
@property  double bottomPadding;                                //@synthesize bottomPadding=_bottomPadding - In the implementation block
@property  BOOL wantsUniformInsetsForSingleColumn;              //@synthesize wantsUniformInsetsForSingleColumn=_wantsUniformInsetsForSingleColumn - In the implementation block
@property  double rowContentPadding;                            //@synthesize rowContentPadding=_rowContentPadding - In the implementation block
@property  double rowContentInset;                              //@synthesize rowContentInset=_rowContentInset - In the implementation block
@property  double rowBackgroundInset;                           //@synthesize rowBackgroundInset=_rowBackgroundInset - In the implementation block
@property  double cornerRadius;                                 //@synthesize cornerRadius=_cornerRadius - In the implementation block
@property  long long selectionMaterial;                         //@synthesize selectionMaterial=_selectionMaterial - In the implementation block
@property  double rowActionsGroupSpacing;                       //@synthesize rowActionsGroupSpacing=_rowActionsGroupSpacing - In the implementation block
@property  double rowActionButtonSpacing;                       //@synthesize rowActionButtonSpacing=_rowActionButtonSpacing - In the implementation block
@property  double rowActionButtonCornerRadius;                  //@synthesize rowActionButtonCornerRadius=_rowActionButtonCornerRadius - In the implementation block
@property  double indentationPerLevel;                          //@synthesize indentationPerLevel=_indentationPerLevel - In the implementation block
@property  double disclosureButtonLeadingSpacing;               //@synthesize disclosureButtonLeadingSpacing=_disclosureButtonLeadingSpacing - In the implementation block
@property  double disclosureButtonWidth;                        //@synthesize disclosureButtonWidth=_disclosureButtonWidth - In the implementation block
@property  double disclosureButtonTrailingSpacing;              //@synthesize disclosureButtonTrailingSpacing=_disclosureButtonTrailingSpacing - In the implementation block
+(instancetype)defaultStyleData;
-(instancetype)initWithEffectiveStyle:(NSTableViewStyle)effectiveStyle API_AVAILABLE(macos(11.0));
-(instancetype)initWithEffectiveStyle:(NSTableViewStyle)effectiveStyle rowSizeStyle:(NSTableViewRowSizeStyle)rowSizeStyle API_AVAILABLE(macos(11.0));

@end
NS_ASSUME_NONNULL_END
