/*
    * This header is generated by classdump-dyld 1.0
    * Operating System: 14.2.1
    * Image Source: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSViewLayerFilter <NSObject>
@required
@property (readonly) BOOL NS_isSourceOver;
@end

